# Generated by Django 4.2.3 on 2024-02-08 16:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shopzero', '0002_product_category_delete_productcategory'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.ImageField(upload_to='product_images/'),
        ),
    ]
