# Generated by Django 4.2.3 on 2024-02-09 17:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shopzero', '0009_remove_cart_quantity_remove_cart_total_price_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cart',
            name='product',
        ),
    ]
