# Generated by Django 4.2.3 on 2024-02-11 16:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shopzero', '0012_alter_wishlist_items'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wishlist',
            name='items',
            field=models.ManyToManyField(blank=True, default=None, to='shopzero.cartitem'),
        ),
    ]
