# Generated by Django 4.2.3 on 2024-02-11 16:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shopzero', '0013_alter_wishlist_items'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='WishListItems',
            new_name='WishListItem',
        ),
    ]
