# Generated by Django 4.2.3 on 2024-02-15 20:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shopzero', '0018_rename_review_review_comment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='rating',
            field=models.PositiveIntegerField(default=1),
        ),
    ]
